name: denovolike
channels:
  - pytorch
  - https://conda.graylab.jhu.edu
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.14.0
  - tensorflow-base=2.14.0
  - pyrosetta=2023.45
  - numpy
  - pandas
  - joblib
  - scikit-learn
  - matplotlib
  - imbalanced-learn