name: denovolike
channels:
  - pytorch
  - https://conda.graylab.jhu.edu
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - cudnn=8.0.5.39
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - pyrosetta=2023.45
  - numpy
  - pandas
  - joblib
  - scikit-learn
  - matplotlib
  - imbalanced-learn
  - pip:
    - tr-rosetta-pytorch==0.0.3
